### ISSUE TITLE
Template list.xml not for this flow

### ISSUE THREAD

**Issue by rothkoe** [tspannhw/nifi-tensorflow-processor#1]
The Template does not fit - it creates a SQL flow

**Comment by tspannhw** [comment]
ill upload a simple onel

**Comment by tspannhw** [comment]
Fixed.  See new template TensorFlowTest.xml

**Comment by rothkoe** [comment]
Thanks ,  ... 

Gesendet mit meinem iPhone

Am 30.09.17 um 16:49 schrieb Timothy Spann
