### ISSUE TITLE
Test required images not includes

### ISSUE THREAD

**Issue by simonellistonball** [tspannhw/nifi-tensorflow-processor#2]
Tests refer to "/Volumes/Transcend/projects/nifi-tensorflow-processor/images/squirrelshirt.jpg" and "/Volumes/Transcend/projects/nifi-tensorflow-processor/models/"

This gives me build failures when running with tests. Would be awesome to get them included as resources and refer the path to with something like 

`URL resource = YourClass.class.getResource("abc"); 
Paths.get(resource.toURI()).toFile();`

I see the models in the repo, but not the image, which given the name somes like something we HAVE to see :)

**Comment by tspannhw** [comment]
will do.  thanks for the tip.

**Comment by simonellistonball** [comment]
@tspannhw in case it helps, I went and did it anyway (PR submitted) along with a few other things I wanted to add in. Still want to see the squirrel shirt though!
